<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>bundleUUID</key>
  <string>2c0b87a8-7841-4eab-a6cc-96a3a5016256</string>
  <key>name</key>
  <string>TestConsole</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>begin</key>
      <string>^(?=[\.\*F]+$)</string>
      <key>end</key>
      <string>$</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\.+</string>
          <key>name</key>
          <string>test.pass</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\*+</string>
          <key>name</key>
          <string>test.pending</string>
        </dict>
        <dict>
          <key>match</key>
          <string>F+</string>
          <key>name</key>
          <string>test.fail</string>
        </dict>
      </array>
    </dict>

    <dict>
      <key>match</key>
      <string>\b\d+ examples?|\b0 failures</string>
      <key>name</key>
      <string>test.pass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b\d+ failures?</string>
      <key>name</key>
      <string>test.fail</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b\d+ pending</string>
      <key>name</key>
      <string>test.pending</string>
    </dict>

    <dict>
      <key>match</key>
      <string>^Failures:</string>
      <key>name</key>
      <string>test.fail</string>
    </dict>
    <dict>
      <key>match</key>
      <string>^Pending:</string>
      <key>name</key>
      <string>test.pending</string>
    </dict>
    <dict>
      <key>match</key>
      <string>^     Failure/Error: .+$</string>
      <key>name</key>
      <string>test.fail</string>
    </dict>

    <dict>
      <key>match</key>
      <string>\s#\s.+</string>
      <key>name</key>
      <string>test.comment</string>
    </dict>
  </array>

  <key>scopeName</key>
  <string>tests.ruby</string>
  <key>uuid</key>
  <string>2c0b87a8-7841-4eab-a6cc-96a3a5016256</string>
</dict>
</plist>
